# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solutionDirectory: 'GraphqlController'
  GraphControllerProjectDirectory: '$(solutionDirectory)/GraphqlController'
  GraphControllerAspNetCoreProjectDirectory: '$(solutionDirectory)/GraphqlController.AspNet'

steps:

# build projects
- script: dotnet build $(solutionDirectory) --configuration $(buildConfiguration)
  displayName: 'Build Projects'

# run tests
- script: dotnet test $(solutionDirectory)
  displayName: 'Run Tests'

# install git version
- script: dotnet tool install --tool-path . GitVersion.Tool --version 5.3.2
  displayName: 'Install GitVersion'

# run GitVersion
- script:  ./dotnet-gitversion /output buildserver



# # create nuget packages
# - script: dotnet pack $(GraphControllerProjectDirectory) --no-build
# - script: dotnet pack $(GraphControllerAspNetCoreProjectDirectory) --no-build