# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pr:
  autoCancel: true
  branches:
    include:
      - master
      - develop
      - releases/*

trigger:
  branches:
    include:  
      - master
      - develop
      - releases/*
  
    

pool:
  vmImage: 'ubuntu-latest'

  
variables:
  buildConfiguration: 'Release'
  solutionDirectory: 'GraphqlController'
  GraphControllerProjectDirectory: '$(solutionDirectory)/GraphqlController'
  GraphControllerAspNetCoreProjectDirectory: '$(solutionDirectory)/GraphqlController.AspNet'

steps:

# install git version
- script: dotnet tool install --tool-path . GitVersion.Tool --version 5.3.2
  displayName: 'Install GitVersion'

# run GitVersion
- script:  ./dotnet-gitversion /output buildserver
  displayName: 'Run GitVersion'


# build projects
- script: dotnet build $(solutionDirectory) --configuration $(buildConfiguration) -p:Version=$(GitVersion.NugetVersion)
  displayName: 'Build Projects'

# run tests
- script: dotnet test $(solutionDirectory)
  displayName: 'Run Tests'

# create nuget packages
- script: dotnet pack $(GraphControllerProjectDirectory) -c $(buildConfiguration) -p:Version=$(GitVersion.NugetVersion) -o . --no-build
  displayName: 'Create Nuget for GraphqlController'

- script: dotnet pack $(GraphControllerAspNetCoreProjectDirectory) -c $(buildConfiguration) -p:Version=$(GitVersion.NugetVersion) -o . --no-build
  displayName: 'Create Nuget for GraphqlController.AspNetCore'

# publish nuget packages
- script: dotnet nuget push ./GraphqlController.$(GitVersion.NugetVersion).nupkg -k $(nugetorgKey) -s https://api.nuget.org/v3/index.json
  displayName: 'Publish GraphqlController'

- script: dotnet nuget push ./GraphqlController.AspNetCore.$(GitVersion.NugetVersion).nupkg -k $(nugetorgKey) -s https://api.nuget.org/v3/index.json
  displayName: 'Publish GraphqlController.AspNetCore'

